### ISSUE TITLE
Sequence contains no elements exception when trying to upload empty Excel file

### ISSUE THREAD

**Issue by ArFreeman** [youngcm2/CsvHelper.Excel#4]
at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at CsvHelper.Excel.ExcelParser..ctor(IXLRangeBase range, CsvConfiguration configuration)
   at CsvHelper.Excel.ExcelParser..ctor(IXLWorksheet worksheet, CsvConfiguration configuration)
   at CsvHelper.Excel.ExcelParser..ctor(XLWorkbook workbook, CsvConfiguration configuration)
   at CsvHelper.Excel.ExcelParser..ctor(Stream stream, CsvConfiguration configuration)

**Comment by youngcm2** [comment]
@ArFreeman which version?
