### ISSUE TITLE
Implementation error

### ISSUE THREAD

**Issue by robertovaldesperez** [youngcm2/CsvHelper.Excel#5]
Hi @youngcm2 , I'm using version 22.1.2.0 of CsvHelper and 15.0.5.0 of CsvHelper.Excel.Core

**System.TypeLoadException: Method 'get_ByteCount' in type 'CsvHelper.Excel.ExcelParser' from assembly 'CsvHelper.Excel, Version=15.0.5.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.**
   at Guru.Service.Master.DataTapeService.Get(Nullable`1 porfolioId)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Guru.Service.Master.DataTapeService.Get(Nullable`1 porfolioId)
   at _dynamic_Guru.Service.Master.DataTapeService.Get(Object , Object[] )
   at Spring.Reflection.Dynamic.SafeMethod.Invoke(Object target, Object[] arguments)
   at Spring.Aop.Framework.DynamicMethodInvocation.InvokeJoinpoint()
   at Spring.Aop.Framework.AbstractMethodInvocation.Proceed()
   at Spring.Transaction.Interceptor.TransactionInterceptor.Invoke(IMethodInvocation invocation)
   at Spring.Aop.Framework.AbstractMethodInvocation.Proceed()
   at Spring.Aop.Framework.DynamicProxy.AdvisedProxy.Invoke(Object proxy, Object target, Type targetType, MethodInfo targetMethod, MethodInfo proxyMethod, Object[] args, IList interceptors)
   at CompositionAopProxy_a65f404572b146259b198b934d28b997.Get(Nullable`1 porfolioId)
   at Guru.Proxy.Master.DataTapeProxy.Get(Nullable`1 porfolioId)
   at Guru.Controllers.Master.DataTapeController.Get(Nullable`1 id)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Hangfire.HangfireDashboardCustomOptionsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

is it possible to update to version 22.1.2.0 of CsvHelper?

**Comment by youngcm2** [comment]
I don't have a test application anymore, but I did update it.

Please try.
https://www.nuget.org/packages/CsvHelper.Excel.Core/22.1.1-beta0001

**Comment by robertovaldesperez** [comment]
Hi @youngcm2 i have this code:

var model = DataTapeRepository.GetAllQueryable().Where(w => w.Id.PorfolioId == porfolioId).FirstOrDefault();
            var fileInfo = FileService.GetContentsByUuid(model.FileInfo.FileUuid);
            using var reader = new CsvReader(new ExcelParser(new System.IO.MemoryStream(fileInfo.Contents), CultureInfo.CurrentCulture));
            var rows = new List<string[]>();
            while (await reader.ReadAsync())
            {
                if (reader.Parser.Read())
                {
                    rows.Add(reader.Parser.Record);
                }
            }
            return rows.ToArray();

and reader.Parser.ReadAsync() return all null and another thing, I don't know how to get the header from the excel

**Comment by robertovaldesperez** [comment]
Sorry everything works fine:

 while (reader.Parser.Read())
            {
                rows.Add(reader.Parser.Record);
            }

**Comment by youngcm2** [comment]
```
var model = DataTapeRepository.GetAllQueryable().Where(w => w.Id.PorfolioId == porfolioId).FirstOrDefault();
var fileInfo = FileService.GetContentsByUuid(model.FileInfo.FileUuid);
using var reader = new CsvReader(new ExcelParser(new System.IO.MemoryStream(fileInfo.Contents), CultureInfo.CurrentCulture));
var rows = new List<string[]>();
while (reader.Read())
{
    rows.Add(reader.GetRecord<string>());
}
return rows.ToArray();
```

**Comment by youngcm2** [comment]
@robertovaldesperez if everything works. I can push that to master and publish 22.1.1

**Comment by robertovaldesperez** [comment]
If I use something like this, 
while (await reader.ReadAsync())
{
    rows.Add(reader.GetRecord<string>());
}

CsvHelper.ReaderException: No header record was found.
IReader state:
   ColumnCount: 0
   CurrentIndex: -1
   HeaderRecord:

IParser state:
   ByteCount: -1
   CharCount: -1
   Row: 2
   RawRow: 2
   Count: 104

   at CsvHelper.CsvReader.ReadHeader()
   at CsvHelper.CsvReader.GetRecord[T]()

i get this error
